apiVersion: v1
kind: Service
metadata:
  name: rust-microservice-service
  namespace: sandbox-ns
spec:
  selector:
    app: rust-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer